//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.BodegaBA.WsAnwoReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsAnwoReference.IWsAnwo")]
    public interface IWsAnwo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/Consultar_productos_disponibles", ReplyAction="http://tempuri.org/IWsAnwo/Consultar_productos_disponiblesResponse")]
        BuenosAires.Model.Respuesta Consultar_productos_disponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/Consultar_productos_disponibles", ReplyAction="http://tempuri.org/IWsAnwo/Consultar_productos_disponiblesResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> Consultar_productos_disponiblesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/reservar_equipo_anwo", ReplyAction="http://tempuri.org/IWsAnwo/reservar_equipo_anwoResponse")]
        BuenosAires.Model.Respuesta reservar_equipo_anwo(string nroserieanwo, char charReservado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/reservar_equipo_anwo", ReplyAction="http://tempuri.org/IWsAnwo/reservar_equipo_anwoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> reservar_equipo_anwoAsync(string nroserieanwo, char charReservado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsAnwoChannel : BuenosAires.BodegaBA.WsAnwoReference.IWsAnwo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsAnwoClient : System.ServiceModel.ClientBase<BuenosAires.BodegaBA.WsAnwoReference.IWsAnwo>, BuenosAires.BodegaBA.WsAnwoReference.IWsAnwo {
        
        public WsAnwoClient() {
        }
        
        public WsAnwoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsAnwoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAnwoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAnwoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.Model.Respuesta Consultar_productos_disponibles() {
            return base.Channel.Consultar_productos_disponibles();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> Consultar_productos_disponiblesAsync() {
            return base.Channel.Consultar_productos_disponiblesAsync();
        }
        
        public BuenosAires.Model.Respuesta reservar_equipo_anwo(string nroserieanwo, char charReservado) {
            return base.Channel.reservar_equipo_anwo(nroserieanwo, charReservado);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> reservar_equipo_anwoAsync(string nroserieanwo, char charReservado) {
            return base.Channel.reservar_equipo_anwoAsync(nroserieanwo, charReservado);
        }
    }
}
