//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.BodegaBA.WsGuiaDespacho {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsGuiaDespacho.IWsGuiaDespacho")]
    public interface IWsGuiaDespacho {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ConsultarGuiasDespacho", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ConsultarGuiasDespachoResponse")]
        BuenosAires.Model.Respuesta ConsultarGuiasDespacho();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ConsultarGuiasDespacho", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ConsultarGuiasDespachoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ConsultarGuiasDespachoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ActualizarEstadoGuiaDespacho", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ActualizarEstadoGuiaDespachoResponse")]
        BuenosAires.Model.Respuesta ActualizarEstadoGuiaDespacho(int p_nrogd, string p_nuevo_estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ActualizarEstadoGuiaDespacho", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ActualizarEstadoGuiaDespachoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ActualizarEstadoGuiaDespachoAsync(int p_nrogd, string p_nuevo_estado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsGuiaDespachoChannel : BuenosAires.BodegaBA.WsGuiaDespacho.IWsGuiaDespacho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsGuiaDespachoClient : System.ServiceModel.ClientBase<BuenosAires.BodegaBA.WsGuiaDespacho.IWsGuiaDespacho>, BuenosAires.BodegaBA.WsGuiaDespacho.IWsGuiaDespacho {
        
        public WsGuiaDespachoClient() {
        }
        
        public WsGuiaDespachoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsGuiaDespachoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGuiaDespachoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGuiaDespachoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.Model.Respuesta ConsultarGuiasDespacho() {
            return base.Channel.ConsultarGuiasDespacho();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ConsultarGuiasDespachoAsync() {
            return base.Channel.ConsultarGuiasDespachoAsync();
        }
        
        public BuenosAires.Model.Respuesta ActualizarEstadoGuiaDespacho(int p_nrogd, string p_nuevo_estado) {
            return base.Channel.ActualizarEstadoGuiaDespacho(p_nrogd, p_nuevo_estado);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ActualizarEstadoGuiaDespachoAsync(int p_nrogd, string p_nuevo_estado) {
            return base.Channel.ActualizarEstadoGuiaDespachoAsync(p_nrogd, p_nuevo_estado);
        }
    }
}
