//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.BodegaBA.WsStockproductoreference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsStockproductoreference.IWsStockProducto")]
    public interface IWsStockProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsStockProducto/ObtenerEquiposEnBodega", ReplyAction="http://tempuri.org/IWsStockProducto/ObtenerEquiposEnBodegaResponse")]
        BuenosAires.Model.Respuesta ObtenerEquiposEnBodega();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsStockProducto/ObtenerEquiposEnBodega", ReplyAction="http://tempuri.org/IWsStockProducto/ObtenerEquiposEnBodegaResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ObtenerEquiposEnBodegaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsStockProductoChannel : BuenosAires.BodegaBA.WsStockproductoreference.IWsStockProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsStockProductoClient : System.ServiceModel.ClientBase<BuenosAires.BodegaBA.WsStockproductoreference.IWsStockProducto>, BuenosAires.BodegaBA.WsStockproductoreference.IWsStockProducto {
        
        public WsStockProductoClient() {
        }
        
        public WsStockProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsStockProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsStockProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsStockProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.Model.Respuesta ObtenerEquiposEnBodega() {
            return base.Channel.ObtenerEquiposEnBodega();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ObtenerEquiposEnBodegaAsync() {
            return base.Channel.ObtenerEquiposEnBodegaAsync();
        }
    }
}
